---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - example.open-cluster-management.io
  resources:
  - hellospokes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.open-cluster-management.io
  resources:
  - hellospokes/finalizers
  verbs:
  - update
- apiGroups:
  - example.open-cluster-management.io
  resources:
  - hellospokes/status
  verbs:
  - get
  - patch
  - update
