apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospoke-agent
  namespace: {{ .AddonInstallNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      addon: example-addon
  template:
    metadata:
      labels:
        addon: example-addon
    spec:
      containers:
      - args:
        - agent
        - --hub-kubeconfig=/var/run/hub/kubeconfig
        - --cluster-name={{ .ClusterName }}
        image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        name: example-addon-agent
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub
      serviceAccountName: hellospoke-agent
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .KubeConfigSecret }}
